spring:
  application:
    name: eurekaserver

  security:
    user:
      name: ${ADMIN_USERNAME:adm}
      password: ${ADMIN_PASSWORD:adm}

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false